dist: trusty
language: node_js
node_js:
  - 12
before_install:
install:
  - npm ci
script:
  - npm test
before_deploy:
  - npm run build 
  - npm install netlify-cli -g
deploy:
  provider: script
  script: netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir ./out
  skip_cleanup: true
  on:
    branch: master